export default {
  APPEND_MOVE: 'APPEND_MOVE',
  CLIENT_START_GAME: 'CLIENT_START_GAME',
  ECHO_ACTION: 'ECHO_ACTION',
  ENGINE_MOVE: 'ENGINE_MOVE',
  LOAD_LEVELS: 'LOAD_LEVELS',
  NEW_OPENING: 'NEW_OPENING',
  PRIME_GUI: 'PRIME_GUI',
  RETRIEVE_LEVELS: 'RETRIEVE_LEVELS',
  SAVE_EVAL: 'SAVE_EVAL',
};
